/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {


        Carro garagem = new Carro("azul", "fusca", new Motor(52, 1500));

        ArrayList<Motor> estante = new ArrayList<>();

        //Troca do motor
        estante.add(garagem.getMotor());

        garagem.setMotor(new Motor(110, 2000));


        garagem = new Carro("vermelho", "Uno", new Motor(40, 1000));




    }
}
