/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

//        Car c = new Car();
//
//        System.out.println("Speed: " + c.getSpeed());
//
//        c.speedUp(100);
//
//        System.out.println("Speed: " + c.getSpeed());
//
//        c.speedDown(90);
//
//        System.out.println("Speed: " + c.getSpeed());
//
        Counter c = new Counter();

        c.countOne();

        System.out.println("Count: " + c.getCount());

        }



    }