/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {

    public static void main(String[] args) {

//        BuzzLightyear b = new BuzzLightyear();
//
//        System.out.println(b.dispararLaser());
//
//        System.out.println("Capacete aberto?" + b.isCapaceteAberto());
//        b.capaceteAbertoFechado();
//        System.out.println("Capacete aberto?" + b.isCapaceteAberto());
//
//        BuzzLightyear malvado = new BuzzLightyear();
//
//        System.out.println("Capacete aberto?" + malvado.isCapaceteAberto());



//        Caneta c = new Caneta();
//
//        c.setCor("Rosa");


        Pessoa p = new Pessoa();

        p.setNome("Enzo");
        p.setCpf("12937912");
        p.setEmail("Enzo@gmail.com");

        System.out.println(p);

    }
}
