/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

import edu.princeton.cs.algs4.Draw;

import java.awt.*;
import java.time.Period;

public class App {


    public static void main(String[] args) {
        Draw draw = new Draw();
        draw.setPenColor(Color.blue);
        draw.filledSquare(.5, .5, 0.3);
        draw.setPenColor(Color.white);
        draw.text(.5,.5,"Emerson");


//        Ajeitar o canva size e tb colocar uma figura

    }
}
